Coqui vignette
jhudsl/text2speech pull request #24
Opened 2023-05-28 05:31 UTC by howardbaek

#### Purpose

I wrote a vignette for using the Coqui TTS engine in text2speech.

#### What changes are being implemented in this Pull Request?

Added `vignettes/coqui-tts.Rmd`

#### What was your approach?

- Gave an introduction to Coqui TTS
- Showed how to install the Coqui TTS executable and check that R knows the correct path to it.
- Talked about functions to list available voices options in Coqui TTS and to convert text to speech using pre-trained models.

#### What GitHub issue does your pull request address?

https://github.com/jhudsl/text2speech/issues/23

#### Tell potential reviewers what kind of feedback you are soliciting.

- Whether the vignette is clear and easy to follow. 
- Any other information that I missed

2023-05-30 12:37 UTC, cansavvy requested changes
This looks excellent! Very well put together and thought out! I have a couple changes I think we should make but I don't think anything will take too much time. 

In addition to these changes, you'll need to resolve some branch stuff. 

1. Merge #20 to main when you are ready. 
2. Merge main into this branch. '
3. Then after you make the necessary edits to this branch we'll be ready for merging this into main (but I might want to review it one more time before that if that's cool).

2023-05-30 12:37 UTC, cansavvy commented on tests/testthat/test-tts_backend.R
> +patrick::with_parameters_test_that("test tts() on Amazon, Google, Microsoft, and Coqui TTS) ",
Is this because you ran `styler`?

2023-05-30 12:37 UTC, cansavvy commented on vignettes/coqui-tts.Rmd
> +Coqui TTS is a text-to-speech (TTS) library that enables the conversion of regular text into speech. It provides pre-trained tts and vocoder models as part of its package. To get a sense of the best
```suggestion
Coqui TTS is a text-to-speech (TTS) library that enables the conversion of regular text into speech and is completely free to use (this is not true of the other text to speech converters used by `text2speech`. 

Coqui TTS provides pre-trained tts and vocoder models as part of its package. To get a sense of the best tts and vocoder models, take a look at this [GitHub Discussion post](https://github.com/coqui-ai/TTS/discussions/1891). In the [Coqui TTS Hugging Face Space](https://huggingface.co/spaces/coqui/CoquiTTS), you have the opportunity to experiment with a few of these models by inputting text and receiving corresponding audio output. 
```

Just want to make it completely clear why one would choose Coqui over the others.

2023-05-30 12:37 UTC, cansavvy commented on vignettes/coqui-tts.Rmd
> +- [Pushing the frontier of neural text to speech](https://youtu.be/MA8PCvmr8B0), a webinar by Xu Tan at Microsoft Research Asia
Great! I love links to more resources. a) we don't have to go over this material but b) The reader still has access to this knowledge if they want it.

2023-05-30 12:37 UTC, cansavvy commented on vignettes/coqui-tts.Rmd
> +## Usage
This section should probably come after `# Installation` since someone can't run these thing before they've installed it.

2023-05-30 12:37 UTC, cansavvy commented on vignettes/coqui-tts.Rmd
> +You have the option to manually specify the path to the Coqui TTS executable in R. This can be done by setting a global option using the `set_coqui_path()` function:
You may want to tell them how they can find their coqui path. 

Isn't it something like: 

```
which tts
```
There may be other ways. What did you run to find you coqui path?

2023-05-30 12:37 UTC, cansavvy commented on vignettes/coqui-tts.Rmd
> +Run a pre-trained model from the [release models list](https://github.com/coqui-ai/TTS#implemented-models), with its default vocoder:
Probably don't need all this information. We want to tell people how to run `text2speech` with coqui, we don't need to tell them how to run coqui except for how it pertains to running `text2speech`.

2023-05-30 12:37 UTC, cansavvy commented on vignettes/coqui-tts.Rmd
> +
For reproducibility purposes you'll want to spit out a sessionInfo so folks know what software environment was used to make this vignette: 
```suggestion
sessionInfo()
```

2023-05-31 00:45 UTC, howardbaek commented
I finished making changes to the vignette. Tagging @cansavvy so you can review one last time before we merge.

2023-05-31 00:51 UTC, cansavvy approved these changes
Looks reasonable to me!! Moving on!

2023-05-31 01:02 UTC, merged